spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/im-db-training-project
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true