spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/im-db-training-project
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
    show-sql: false