spring:
  application:
    name: messenger
  jersey:
    application-path: api
  thymeleaf:
    # Whether to check that the template exists before rendering it.
    check-template: true
    # Whether to check that the templates location exists.
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
  datasource:
    url: jdbc:postgresql://localhost:5432/im-db-training-project
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /im-webapp