DROP SCHEMA legacy_im_db_schema CASCADE;

CREATE SCHEMA legacy_im_db_schema AUTHORIZATION postgres;

COMMENT ON SCHEMA legacy_im_db_schema IS 'instant messenger web application - vironit training project ';

-- Drop table

-- DROP TABLE legacy_im_db_schema.roles;

CREATE TABLE legacy_im_db_schema.roles (
	id serial NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT roles_pk PRIMARY KEY (id)
);

-- DROP SEQUENCE legacy_im_db_schema.users_id_seq;

CREATE SEQUENCE legacy_im_db_schema.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.users;

CREATE TABLE legacy_im_db_schema.users (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.users_id_seq'),
	firstname varchar(150) NULL,
	lastname varchar(150) NULL,
	nickname varchar(60) NOT NULL,
	email varchar(160) NOT NULL,
	salt bytea NOT NULL,
	passwordhash varchar(160) NOT NULL,
	enabled bool NOT NULL,
	id_role int4 NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_fk1 FOREIGN KEY (id_role) REFERENCES legacy_im_db_schema.roles(id) ON UPDATE CASCADE
);
CREATE UNIQUE INDEX users_email_idx ON legacy_im_db_schema.users USING btree (email);
--ALTER SEQUENCE legacy_im_db_schema.user_id_seq OWNED BY users.id;

-- Drop table

-- DROP TABLE legacy_im_db_schema.chatroom_privileges;

CREATE TABLE legacy_im_db_schema.chatroom_privileges (
	id serial NOT NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT chatroom_privileges_pk PRIMARY KEY (id)
);

-- DROP SEQUENCE legacy_im_db_schema.chatrooms_id_seq;

CREATE SEQUENCE legacy_im_db_schema.chatrooms_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.chatrooms;

CREATE TABLE legacy_im_db_schema.chatrooms (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.chatrooms_id_seq'),
	"name" varchar(150) NOT NULL,
	timecreated timestamp NOT NULL,
	public bool NOT NULL,
	CONSTRAINT chatrooms_pk PRIMARY KEY (id)
);

--## ALTER SEQUENCE chatrooms_id_seq OWNED BY chatrooms.id;

-- DROP SEQUENCE legacy_im_db_schema.contacts_id_seq;

CREATE SEQUENCE legacy_im_db_schema.contacts_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.contacts;

CREATE TABLE legacy_im_db_schema.contacts (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.contacts_id_seq'),
	id_owner int8 NOT NULL,
	id_person int8 NOT NULL,
	confirmed bool NOT NULL DEFAULT false,
	CONSTRAINT contacts_pk PRIMARY KEY (id),
	CONSTRAINT subscriptions_fk FOREIGN KEY (id_owner) REFERENCES legacy_im_db_schema.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT subscriptions_fk_1 FOREIGN KEY (id_person) REFERENCES legacy_im_db_schema.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX contacts_id_owner_idx ON legacy_im_db_schema.contacts USING btree (id_owner);
CREATE INDEX contacts_id_person_idx ON legacy_im_db_schema.contacts USING btree (id_person, id_owner);

--## ALTER SEQUENCE contacts_id_seq OWNED BY contacts.id;

-- Drop table

-- DROP TABLE legacy_im_db_schema.imagemessageresources;

CREATE TABLE legacy_im_db_schema.imagemessageresources (
	id bigserial NOT NULL,
	"name" varchar(150) NOT NULL,
	imagebin bytea NOT NULL,
	width int4 NOT NULL,
	height int4 NOT NULL,
	CONSTRAINT imagemessageresources_pk PRIMARY KEY (id)
);

-- DROP SEQUENCE legacy_im_db_schema.messages_id_seq;

CREATE SEQUENCE legacy_im_db_schema.messages_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.messages;

CREATE TABLE legacy_im_db_schema.messages (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.messages_id_seq'),
	messagetype varchar(45) NOT NULL,
	body varchar(500) NOT NULL,
	timesent timestamp NOT NULL,
	id_contact int8 NULL,
	id_author int8 NOT NULL,
	id_messageresource int8 NULL,
	id_chatroom int8 NULL,
	CONSTRAINT message_pk PRIMARY KEY (id),
	CONSTRAINT private_messages_fk FOREIGN KEY (id_contact) REFERENCES legacy_im_db_schema.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT private_messages_fk1 FOREIGN KEY (id_author) REFERENCES legacy_im_db_schema.users(id) ON UPDATE CASCADE,
	CONSTRAINT private_messages_fk3 FOREIGN KEY (id_chatroom) REFERENCES legacy_im_db_schema.chatrooms(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX message_timesent_idx ON legacy_im_db_schema.messages USING btree (timesent);
CREATE INDEX private_messages_id_author_idx ON legacy_im_db_schema.messages USING btree (id_author);

--## ALTER SEQUENCE messages_id_seq OWNED BY messages.id;

-- DROP SEQUENCE legacy_im_db_schema.subscriptions_id_seq;

CREATE SEQUENCE legacy_im_db_schema.subscriptions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.subscriptions;

CREATE TABLE legacy_im_db_schema.subscriptions (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.subscriptions_id_seq'),
	id_user int8 NOT NULL,
	id_chatroom int8 NOT NULL,
	enteredchat timestamp NOT NULL,
	enabled bool NOT NULL,
	id_userprivilege int4 NOT NULL DEFAULT 0,
	CONSTRAINT subscriptions_pk PRIMARY KEY (id),
	CONSTRAINT subscriptions_fk FOREIGN KEY (id_userprivilege) REFERENCES legacy_im_db_schema.chatroom_privileges(id) ON UPDATE CASCADE,
	CONSTRAINT users_has_chatrooms_fk FOREIGN KEY (id_user) REFERENCES legacy_im_db_schema.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT users_has_chatrooms_fk_1 FOREIGN KEY (id_chatroom) REFERENCES legacy_im_db_schema.chatrooms(id) ON UPDATE CASCADE ON DELETE CASCADE
);

--## ALTER SEQUENCE subscriptions_id_seq OWNED BY subscriptions.id;

-- DROP SEQUENCE legacy_im_db_schema.messageresources_id_seq;

CREATE SEQUENCE legacy_im_db_schema.messageresources_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	CACHE 1
	NO CYCLE;

-- Drop table

-- DROP TABLE legacy_im_db_schema.messageresources;

CREATE TABLE legacy_im_db_schema.messageresources (
	id bigint NOT NULL DEFAULT nextval('legacy_im_db_schema.messageresources_id_seq'),
	id_message int8 NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT messageresource_pk PRIMARY KEY (id),
	CONSTRAINT messageresource_fk FOREIGN KEY (id_message) REFERENCES legacy_im_db_schema.messages(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT messageresource_fk1 FOREIGN KEY (id) REFERENCES legacy_im_db_schema.imagemessageresources(id) ON UPDATE CASCADE ON DELETE CASCADE
);

--## ALTER SEQUENCE messageresources_id_seq OWNED BY messageresources.id;


INSERT INTO legacy_im_db_schema.roles
("name")
VALUES('ADMIN');
INSERT INTO legacy_im_db_schema.roles
("name")
VALUES('USER');

INSERT INTO legacy_im_db_schema.chatroom_privileges
("name")
VALUES('CHATADMIN');
INSERT INTO legacy_im_db_schema.chatroom_privileges
("name")
VALUES('COMMONER');

INSERT INTO legacy_im_db_schema.users
(firstname, lastname, nickname, email, salt, passwordhash, enabled, id_role)
VALUES('Vladimir', 'Putin', 'Vlad', 'bad@mail.ru', decode('ffff', 'hex'), '036a6b0638ebe1a8b59b964a4477255f5490b6b9c9f9fbd7cc105062d0fa66e9cef42ea63a2037a5aac7abaa11dee6de647f5605a8022954498e4d41c32aa91a', true, 1);
